[package]
name = "curvine-client"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curvine-client-core = { workspace = true }
curvine-job-client = { workspace = true, optional = true }
curvine-unified-fs = { workspace = true, optional = true }
curvine-bench = { workspace = true, optional = true }

[features]
default = []

job-client = ["dep:curvine-job-client"]
unified = ["dep:curvine-unified-fs"]
bench = ["dep:curvine-bench", "unified"]
opendal = ["unified", "curvine-unified-fs/opendal"]
opendal-s3 = ["unified", "curvine-unified-fs/opendal-s3"]
opendal-oss = ["unified", "curvine-unified-fs/opendal-oss"]
opendal-gcs = ["unified", "curvine-unified-fs/opendal-gcs"]
opendal-azblob = ["unified", "curvine-unified-fs/opendal-azblob"]
opendal-cos = ["unified", "curvine-unified-fs/opendal-cos"]
opendal-hdfs = ["unified", "curvine-unified-fs/opendal-hdfs"]
opendal-webhdfs = ["unified", "curvine-unified-fs/opendal-webhdfs"]
opendal-hdfs-native = ["unified", "curvine-unified-fs/opendal-hdfs-native"]
oss-hdfs = ["unified", "curvine-unified-fs/oss-hdfs"]
