// Copyright 2025 OPPO.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use clap::Parser;
use curvine_config::{ClientConfCliOverrides, ClusterConf, FuseConfCliOverrides};
use curvine_core_error::{err_box, CommonResult};
use curvine_net::net::InetAddr;
use curvine_sys::version;

/// CLI arguments for the curvine-fuse mount command.
///
/// The per-field `[fuse]` tunables (`--io-threads`, `--web-port`, …) are no
/// longer hand-written here: `FuseConfCliOverrides` is generated by the
/// `ClientCliArgs` derive on `FuseConf` (opt-in), so the CLI surface and the
/// config struct cannot drift apart. Only arguments without a 1:1 scalar field
/// mapping stay hand-written: `--debug`/`--readonly` (SetTrue semantics), the
/// `--options` list, and `--master-addrs` (client-section parse).
#[derive(Debug, Parser, Clone)]
#[command(version = version::VERSION)]
pub struct FuseMountArgs {
    #[command(flatten)]
    pub fuse: FuseConfCliOverrides,

    #[arg(
        short,
        long,
        action = clap::ArgAction::SetTrue,
        help = "Enable debug mode"
    )]
    debug: bool,

    #[arg(
        short,
        long,
        help = "Configuration file path (optional)",
        default_value = "conf/curvine-cluster.toml"
    )]
    conf: String,

    #[arg(long, help = "Master address (e.g., 'm1:8995,m2:8995')")]
    pub master_addrs: Option<String>,

    // FUSE options
    #[arg(
        short,
        long,
        help = "FUSE options; when provided, replace options from the config file"
    )]
    options: Vec<String>,

    #[arg(
        long,
        action = clap::ArgAction::SetTrue,
        help = "Mount the entire FUSE filesystem read-only"
    )]
    readonly: bool,
}

impl FuseMountArgs {
    /// Parses the cluster configuration file and applies CLI overrides.
    pub fn get_conf(&self) -> CommonResult<ClusterConf> {
        let mut conf = ClusterConf::from(&self.conf)?;
        println!("Loaded configuration from {}", self.conf);

        // Generated [fuse] overrides — one apply_to instead of ~30 branches.
        self.fuse.apply_to(&mut conf.fuse)?;

        if self.debug {
            conf.fuse.debug = true;
        }

        if self.readonly {
            conf.fuse.readonly = true;
        }

        if let Some(master_addrs) = &self.master_addrs {
            let vec = match InetAddr::parse_list(master_addrs) {
                Ok(vec) => vec,
                Err(e) => {
                    return err_box!("wrong format master_addrs {}: {}", master_addrs, e);
                }
            };
            conf.client.master_addrs = vec;
        }

        // CLI options replace config-file options when provided. Otherwise preserve
        // configured options and apply defaults only when neither source supplies any.
        if !self.options.is_empty() {
            conf.fuse.fuse_opts = self.options.clone()
        } else if conf.fuse.fuse_opts.is_empty() {
            conf.fuse.fuse_opts = Self::default_mnt_opts();
        }

        conf.fuse.init()?;
        conf.fuse.normalize_fuse_opts()?;

        Ok(conf)
    }

    pub fn default_mnt_opts() -> Vec<String> {
        if cfg!(feature = "fuse3") {
            vec!["allow_other".to_string(), "async".to_string()]
        } else {
            vec![
                "allow_other".to_string(),
                "async".to_string(),
                "big_write".to_string(),
            ]
        }
    }
}

/// Mount CLI flags plus generated `ClientConf` overrides (`--client.*`).
#[derive(Debug, Parser, Clone)]
pub struct FuseRuntimeArgs {
    #[command(flatten)]
    pub mount: FuseMountArgs,

    #[command(flatten)]
    pub client: ClientConfCliOverrides,
}

impl FuseRuntimeArgs {
    /// Loads cluster config from mount flags and applies `--client.*` overrides.
    pub fn get_conf(&self) -> CommonResult<ClusterConf> {
        let mut conf = self.mount.get_conf()?;
        self.client.apply_to(&mut conf.client)?;
        conf.client.init()?;
        Ok(conf)
    }

    /// Path to the configuration file that `get_conf` loads from. Used by
    /// `validate-config` to re-read the raw TOML for unknown-key detection.
    pub fn conf_path(&self) -> &str {
        &self.mount.conf
    }
}

#[cfg(test)]
mod tests {
    use super::FuseMountArgs;
    use clap::Parser;
    use curvine_config::ClusterConf;
    use curvine_core_error::CommonResult;
    use curvine_runtime::common::Utils;
    use std::fs;

    fn try_get_conf(config: &str, extra_args: &[&str]) -> CommonResult<ClusterConf> {
        let conf_path = Utils::temp_file();
        fs::write(&conf_path, config).expect("write test config");

        let mut argv = vec!["curvine-fuse", "--conf", conf_path.as_str()];
        argv.extend_from_slice(extra_args);
        let args = FuseMountArgs::try_parse_from(argv).expect("parse mount arguments");
        let result = args.get_conf();
        let _ = fs::remove_file(&conf_path);

        result
    }

    fn get_conf(config: &str, extra_args: &[&str]) -> ClusterConf {
        try_get_conf(config, extra_args).expect("load mount configuration")
    }

    #[test]
    fn get_conf_preserves_config_fuse_opts_without_cli_override() {
        let conf = get_conf(
            "[fuse]\nio_threads = 1\nfuse_opts = [\"allow_other\", \"ro\"]\n",
            &[],
        );

        assert_eq!(conf.fuse.fuse_opts, vec!["allow_other", "ro"]);
    }

    #[test]
    fn get_conf_cli_fuse_opts_replace_config_fuse_opts() {
        let conf = get_conf(
            "[fuse]\nio_threads = 1\nfuse_opts = [\"allow_other\"]\n",
            &["--options", "ro"],
        );

        assert_eq!(conf.fuse.fuse_opts, vec!["ro"]);
    }

    #[test]
    fn generated_overrides_apply_io_threads() {
        let conf = get_conf("[fuse]\nio_threads = 1\n", &["--io-threads", "4"]);
        assert_eq!(conf.fuse.io_threads, 4);
    }

    #[test]
    fn tasks_per_mnt_keeps_legacy_alias() {
        // `--mnt-per-task` is the pre-refactor spelling; both must work.
        let via_alias = get_conf("[fuse]\n", &["--mnt-per-task", "3"]);
        assert_eq!(via_alias.fuse.tasks_per_mnt, 3);

        let via_canonical = get_conf("[fuse]\n", &["--tasks-per-mnt", "5"]);
        assert_eq!(via_canonical.fuse.tasks_per_mnt, 5);
    }

    #[test]
    fn meta_cache_ttl_flag_maps_to_timeout_field() {
        let conf = get_conf("[fuse]\n", &["--meta-cache-ttl", "90s"]);
        assert_eq!(conf.fuse.meta_cache_timeout, "90s");
    }

    #[test]
    fn debug_and_readonly_stay_set_true_flags() {
        let plain = get_conf("[fuse]\n", &[]);
        assert!(!plain.fuse.debug);

        let debugged = get_conf("[fuse]\n", &["-d"]);
        assert!(debugged.fuse.debug);
    }

    #[test]
    fn master_addrs_override_reaches_client_section() {
        let conf = get_conf("[fuse]\nio_threads = 1\n", &["--master-addrs", "m1:8995"]);
        assert_eq!(conf.client.master_addrs[0].hostname, "m1");
        assert_eq!(conf.client.master_addrs[0].port, 8995);
    }

    #[test]
    fn get_conf_rejects_zero_io_threads_cli_override() {
        // Wiring check: apply_to result must still flow through
        // FuseConf::init() inside get_conf.
        let conf_path = Utils::temp_file();
        fs::write(&conf_path, "[fuse]\nio_threads = 1\n").expect("write test config");

        let args = FuseMountArgs::try_parse_from([
            "curvine-fuse",
            "--conf",
            conf_path.as_str(),
            "--io-threads",
            "0",
        ])
        .expect("parse mount arguments");
        let result = args.get_conf();
        let _ = fs::remove_file(&conf_path);

        let err = result.expect_err("zero io_threads override must be rejected");
        assert!(
            err.to_string().contains("fuse.io_threads must be > 0"),
            "unexpected error: {}",
            err
        );
    }

    #[test]
    fn get_conf_applies_default_mnt_opts_when_neither_source_supplies_any() {
        // Wiring check: the default-options fallback lives in get_conf.
        let conf_path = Utils::temp_file();
        fs::write(&conf_path, "[fuse]\nio_threads = 1\n").expect("write test config");

        let args = FuseMountArgs::try_parse_from(["curvine-fuse", "--conf", conf_path.as_str()])
            .expect("parse mount arguments");
        let result = args.get_conf();
        let _ = fs::remove_file(&conf_path);

        let conf = result.expect("load mount configuration");
        assert!(
            !conf.fuse.fuse_opts.is_empty(),
            "defaults must apply when neither CLI nor config supply fuse_opts"
        );
    }

    #[test]
    fn get_conf_includes_parse_error_for_invalid_master_addrs() {
        let conf_path = Utils::temp_file();
        fs::write(&conf_path, "[fuse]\nio_threads = 1\n").expect("write test config");

        let args = FuseMountArgs::try_parse_from([
            "curvine-fuse",
            "--conf",
            conf_path.as_str(),
            "--master-addrs",
            "host-a:8995, host-b:not-a-port",
        ])
        .expect("parse mount arguments");
        let result = args.get_conf();
        let _ = fs::remove_file(&conf_path);

        let err = result.expect_err("invalid master_addrs must fail");
        let msg = err.to_string();
        assert!(
            msg.contains("wrong format master_addrs host-a:8995, host-b:not-a-port"),
            "unexpected error: {msg}"
        );
        assert!(
            msg.contains("invalid digit found in string"),
            "parse error should be included: {msg}"
        );
    }

    #[test]
    fn unset_flags_keep_config_values() {
        let conf = get_conf(
            "[fuse]\nio_threads = 2\nweb_port = 9100\ndirect_io = true\n",
            &[],
        );
        assert_eq!(conf.fuse.io_threads, 2);
        assert_eq!(conf.fuse.web_port, 9100);
        assert!(conf.fuse.direct_io);
    }
}
