[package]
name = "curvine-net"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Curvine network primitives."

[dependencies]
curvine-io = { workspace = true }
curvine-core-error = { workspace = true }
curvine-runtime = { workspace = true }
serde = { workspace = true }
sysinfo = { workspace = true }
tokio = { workspace = true }
