# Whether to format it.  
# master formatting will delete rocksdb metadata  
# Worker formatting will delete the data directory.  
format_master = true  
format_worker = true  

# master configuration  
[master]  
meta_dir = "testing/meta"  
log = { level = "info", log_dir = "stdout", file_name = "master.log" }  
  
  
# master ha raft configuration.  
[journal]  
journal_addrs = [  
    {id = 1, hostname = "localhost", port = 8996}  
]  
journal_dir = "testing/journal"  
  
  
# Worker configuration  
[worker]  
dir_reserved = "0"  
data_dir = [  
    "[SPDK_DISK]testing/data", 
] 
log = { level = "debug", log_dir = "stdout", file_name = "worker.log" }  
enable_s3_gateway = false  

io_threads=2
worker_threads=2
  
# SPDK over NVMe-oF/TCP configuration  
[worker.spdk_disk]  
enabled = true  
app_name = "curvine"  
hugepage = "10MB"
reactor_mask = "0x30"  
# NVMe-oF targets  
[[worker.spdk_disk.targets]]
trtype = "tcp"  
adrfam = "ipv4"  
traddr = "127.0.0.1"  
trsvcid = 4420  
subnqn = "nqn.2026-05.curvine:cnode1"  

# Client configuration  
[client]
short_circuit = false

# fuse configuration  
[fuse]  
  
# Log configuration  
[log]  
level = "debug"  
log_dir = "stdout"  
file_name = "curvine.log"  
  
  
# S3 Object Gateway configuration  
[s3_gateway]  
listen = "0.0.0.0:9900"  
region = "us-east-1"  
put_temp_dir = "/tmp/curvine-temp"  
put_memory_buffer_threshold = 1048576  
put_max_memory_buffer = 16777216  
get_chunk_size_mb = 1.0  
  
[cli]  
log = { level = "warn", log_dir = "stdout", file_name = "cli.log" }