[package]
name = "curvine-model"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
curvine-error = { workspace = true }
curvine-proto = { workspace = true }
curvine-sys = { workspace = true }
curvine-core-error = { workspace = true }
curvine-net = { workspace = true }
curvine-runtime = { workspace = true }
serde = { workspace = true }
prost = { workspace = true }
bincode = { workspace = true }
log = { workspace = true }
num_enum = { workspace = true }
indexmap = { workspace = true }
clap = { workspace = true }
bitflags = { workspace = true }
chrono = { workspace = true }

[features]
default = []

[dev-dependencies]
curvine-fs-api = { workspace = true }
